kind: Namespace
apiVersion: v1
metadata:
  name: dev-apps
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-app-deployment
  namespace: dev-apps
  labels:
    app: upload-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-ap
  template:
    metadata:
      labels:
        app: upload-ap
    spec:
      containers:
      - name: upload-ap
        image: 454654/app-images:upload-app-v1
        ports:
        - containerPort: 80
      tolerations:
      - effect: NoSchedule
        key: SaaSCloudServices
        operator: Equal
        value: Allowed

